### ISSUE TITLE
Allow creation of multiple local collection

### ISSUE THREAD

**Issue by mngibso** [vazco/meteor-universe-collection#2]
Mongo.Collection allows you to create "an unmanaged (unsynchronized) local collection" by sending null in place of name:

    var LocalCollection = new Mongo.Collection(null);

I can do this with *one* UniCollection, but if I try to create a second local UniCollection I get the following error:

    Uncaught Error: Type nullDoc already present   ejson.js:110

**Comment by cristo-rabani** [comment]
Hello, 

It's because we didn't anticipate uses without connection to mongo.
But we can fix it for you, for now you can create named local collection (with options.connection = null).

```
localUniColl = new UniCollection('localA', {connection: null});
```

This bug is because:
Serialization of documents is signed as collectionName +'Doc',and in yours case name is null, so you have nullDoc as Json type.

We can fix it by generating random name for EJson type in situation like yours.

So, In the next version it will be fixed. 

Thank you

**Comment by cristo-rabani** [comment]
Our team decided that name should be required. This is important to EJson type, without name we cannot guarantee proper deserialization.

and this is official way to create local collection:

```
localUniColl = new UniCollection('localA', {connection: null});
```
But If someone create with name = null 
Only console.error will be shown in console, not the exception.

**Comment by mngibso** [comment]
Perfect, thanks!  I didn't know the official way to create a local collection
